def init_ui(self):
    ...
    self.root.geometry('900x1050')  # Update window geometry
    ...
    self.grid_columnconfigure(0, weight=1)
    self.grid_rowconfigure(6, weight=1)  # Added to fix layout for the download button
    ...
